[runtime]
; The test sampler evaluates the likelihood once at the fiducial values
sampler = test
root = ${PWD}
verbosity = quiet

[output]
filename = output/des-dovekie.txt
format = text

[pipeline]
modules = consistency astropy des_dovekie
values = examples/des_dovekie_values.ini

[des_dovekie]
file = likelihood/des-dovekie/des_dovekie_like.py
likelihood_only = T

[test]
save_dir=output/des-dovekie

[astropy]
file = background/astropy_background/astropy_background.py
model = lambdacdm
nz = 200
zmax = 2.0

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want
[consistency]
file = utility/consistency/consistency_interface.py
