;
;

[cosmological_parameters]
omega_m      =  0.2   0.31  0.4 #0.1   0.31      0.5
h0           =  0.5  0.68  0.86 #0.9
omega_b      =  0.048  0.049 0.05 #0.01  0.049 0.1
n_s          =  0.95  0.97  1.0 #0.8  0.97  1.2
w            =  -2. -0.838 -0.3 #-3. -0.838 -0.3 #DR2+CMB+Pantheon
wa           = -2. -0.62 0.5 #-3. -0.62 3. #DR2+CMB+Pantheon
;S_8 = 0.8  0.84    0.88
log1e10As = 1.6 3.044 4.
tau          = 0.08

[halo_model_parameters]
logT_AGN = 7.3 7.8 8.0 #6.5 7.8 9.3



[bin_bias]
b1  = 0.5  1.2497 3.0
b2  = 0.5  1.3809 3.0
b3  = 0.5  1.5231 3.0
b4  = 0.5  1.6716 3.0
b5  = 0.5  1.8245 3.0


[intrinsic_alignment_parameters]
;A = -5. 0.4 5.0
;alpha = -5. 2.2 5.
;z0 = 0.
z_piv   =  0.
A1      = -1.6   -0.4  1.2
A2      = 0.0
alpha1  = 0.1  2.2  5.0 #-5.0  1.66  5.0
alpha2  = 0.
bias_ta =  0.0

[number_density_source_params]
alpha = 2.0
; for Y1 use
beta = 0.78
z0 = 0.13
ngal = 10.
;beta = 0.68
;z0 = 0.11
;ngal = 27.0
sigz = 0.05
bias = 0.0

[number_density_lens_params]
alpha = 2.0
; for Y1 use
beta = 0.78
z0 = 0.13
ngal = 10.
;beta = 0.68
;z0 = 0.11
;ngal = 27.0
sigz = 0.03
bias = 0.0

[photoz_source_errors]
bias_1 = -0.1   0.0   0.1
bias_2 = -0.1   0.0   0.1
bias_3 = -0.1   0.0   0.1
bias_4 = -0.1   0.0   0.1
bias_5 = -0.1   0.0   0.1

[photoz_lens_errors]
bias_1 = -0.1   0.0   0.1
bias_2 = -0.1   0.0   0.1
bias_3 = -0.1   0.0   0.1
bias_4 = -0.1   0.0   0.1
bias_5 = -0.1   0.0   0.1

; [mag_alpha_lens]
; alpha_1 = 0.265
; alpha_2 = 0.611
; alpha_3 = 0.768	
; alpha_4 = 0.557	
; alpha_5 = 0.627	



[shear_calibration_parameters]
m1 = -0.1  0.0  0.1
m2 = -0.1  0.0  0.1 
m3 = -0.1  0.0  0.1
m4 = -0.1  0.0  0.1
m5 = -0.1  0.0  0.1








